name: pouch
description: A Personal Finance App

publish_to: 'none'

version: 0.0.4+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.3.3
  salomon_bottom_bar: ^3.3.1
  glass_kit: ^2.0.1
  objectbox: ^1.8.2
  objectbox_flutter_libs: ^1.8.2
  path_provider: ^2.1.1
  path: ^1.9.0
  flat_buffers: ^2.0.8
  intl: ^0.18.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  objectbox_generator: ^1.8.2
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png

objectbox:
  output_dir: objectbox-models



flutter_native_splash:
  color: "#413ABB"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
  fullscreen: false